### ISSUE TITLE
How to prepare conditioned image to iamge task?

### ISSUE THREAD

**Issue by LT1st** [GuHuangAI/DDM-Public#4]

**Comment by LT1st** [comment]
```
data:
  name: edge
  img_folder: '/home/zhuchenyang/project/hyx/data/total_edges'
  augment_horizontal_flip: True
  batch_size: 8

```

I want to train a style transfer task on it, but cannot find how to load data
